source("D:/R_projects/revision_analysis/Code/Revision_v2/R00_config.R")
r2 <- readRDS(file.path(OUT,"intermediate","R02_wgcna.rds"))
r3 <- readRDS(file.path(OUT,"intermediate","R03_translation_module.rds"))
cat("r2 names:", paste(names(r2), collapse=", "), "\n")
cat("kmeHF class:", class(r2$kmeHF), " dim:", paste(dim(r2$kmeHF), collapse="x"), "\n")
cat("kmeHF cols:", paste(head(colnames(r2$kmeHF),8), collapse=", "), "\n")
print(head(r2$kmeHF, 3))
cat("\nHF modules:", paste(unique(r2$HF$net$colors), collapse=","), "\n")
cat("HCC modules:", paste(unique(r2$HCC$net$colors), collapse=","), "\n")
cat("\ncolors HF purple n =", sum(r2$HF$net$colors=="purple"),
    "; HCC magenta n =", sum(r2$HCC$net$colors=="magenta"), "\n")
cat("\ncommon(universe) length:", length(r2$U), "\n")
cat("gxHF dim:", paste(dim(r2$gxHF), collapse="x"), " gxHCC:", paste(dim(r2$gxHCC), collapse="x"), "\n")
cat("\nr5 cohort names:", paste(names(readRDS(file.path(OUT,"intermediate","R05_cohorts.rds"))), collapse=", "), "\n")
cat("\nr6 names:", paste(names(readRDS(file.path(OUT,"intermediate","R06_ssgsea.rds"))), collapse=", "), "\n")
r11 <- readRDS(file.path(OUT,"intermediate","R11_composition.rds"))
cat("\nr11 names:", paste(names(r11), collapse=", "), "\n")
cat("r11 scores cohort:", paste(names(r11$scores), collapse=", "), "\n")
cat("r11 score cols:", paste(colnames(r11$scores[[1]]), collapse=", "), "\n")
