source("D:/R_projects/revision_analysis/Code/Revision_v2/R00_config.R")

w <- readRDS(file.path(OUT, "intermediate", "R02_wgcna.rds"))
cat("=== R02$HF ===\n"); for (n in names(w$HF)) cat(sprintf("  %-16s %s\n", n, paste(class(w$HF[[n]]), collapse="/")))
cat("=== R02$HCC ===\n"); for (n in names(w$HCC)) cat(sprintf("  %-16s %s\n", n, paste(class(w$HCC[[n]]), collapse="/")))
cat("\nmodule_trait_HF traits: ", paste(unique(w$module_trait_HF$trait), collapse=", "), "\n")
cat("head module_trait_HF:\n"); print(head(w$module_trait_HF, 6), row.names=FALSE)
cat("\nMEs HF dim: ", paste(dim(w$HF$MEs), collapse="x"), " | cn: ", paste(head(colnames(w$HF$MEs),8), collapse=","), "\n")
cat("MEs HCC dim: ", paste(dim(w$HCC$MEs), collapse="x"), " | cn: ", paste(head(colnames(w$HCC$MEs),8), collapse=","), "\n")
cat("colors HF: ", paste(head(w$HF$colors, 20), collapse=","), "\n")
cat("n modules HF: ", length(unique(w$HF$colors)), " | HCC: ", length(unique(w$HCC$colors)), "\n")

cat("\n=== R04$table columns ===\n"); print(names(w <- NULL))
r4 <- readRDS(file.path(OUT, "intermediate", "R04_preservation.rds"))
cat(paste(names(r4$table), collapse="\n"), "\n")
cat("\n--- medianRank-ish values, first 6 rows ---\n")
mr <- grep("rank", names(r4$table), ignore.case=TRUE, value=TRUE)
cat("rank cols:", paste(mr, collapse=", "), "\n")
print(head(r4$table[, c("reference","test","module","moduleSize","Zsummary.pres", mr)], 6), row.names=FALSE)
cat("\nreference values:", paste(unique(r4$table$reference), collapse=", "), "\n")
cat("test values:", paste(unique(r4$table$test), collapse=", "), "\n")

cat("\n=== R06 cohort/disease map ===\n")
r6 <- readRDS(file.path(OUT, "intermediate", "R06_ssgsea.rds"))
print(r6$sizes, row.names=FALSE)

cat("\n=== R12$scores names ===\n"); r12 <- readRDS(file.path(OUT, "intermediate", "R12_tats_tf.rds"))
cat(paste(names(r12$scores), collapse=", "), "\n")
cat("=== R12$gs ===\n"); print(r12$gs, row.names=FALSE)

cat("\n=== R15$stages ===\n"); r15 <- readRDS(file.path(OUT, "intermediate", "R15_cirrhosis_control.rds"))
cat(paste(r15$stages, collapse=" | "), "\n")
cat("=== R15$crosscheck ===\n"); print(r15$crosscheck, row.names=FALSE, digits=3)
cat("\nPROBE DONE\n")
