o <- readRDS("D:/R_projects/revision_analysis/v2_output/intermediate/R01_universe.rds")
cat("U size:", length(o$U), "\n")
cat("HF samples:", ncol(o$E_hf_full), " HCC samples:", ncol(o$E_hcc_full), "\n\n")
cat("=== HF group x etiology ===\n"); print(table(o$ann_hf$group, o$ann_hf$etiology, useNA = "ifany"))
cat("\n=== HF group x gender ===\n"); print(table(o$ann_hf$group, o$ann_hf$gender, useNA = "ifany"))
cat("\n=== HF group counts ===\n"); print(table(o$ann_hf$group, useNA = "ifany"))
cat("\nDCM:", sum(o$ann_hf$etiology == "DCM", na.rm = TRUE),
    " ICM:", sum(o$ann_hf$etiology == "ICM", na.rm = TRUE), "\n")
cat("\n=== range checks ===\n")
cat("HF expr range:", sprintf("%.2f .. %.2f", min(o$E_hf_full), max(o$E_hf_full)), "\n")
cat("HCC expr range:", sprintf("%.2f .. %.2f", min(o$E_hcc_full), max(o$E_hcc_full)), "\n")
cat("\n=== per-sample medians (first 5 each) ===\n")
cat("HF :", sprintf("%.2f", apply(o$E_hf_full, 2, median)[1:5]), "\n")
cat("HCC:", sprintf("%.2f", apply(o$E_hcc_full, 2, median)[1:5]), "\n")
