source("D:/R_projects/revision_analysis/Code/Revision_v2/R00_config.R")
sm <- parse_series_matrix(file.path(DATA_RAW,"GSE14520-GPL3921_series_matrix.txt.gz"))
cat("dim:", paste(dim(sm$expr),collapse="x"), "\n")
cat("rownames head:", paste(head(rownames(sm$expr),4),collapse=", "), "\n")
cat("range:", sprintf("%.3f .. %.3f", min(sm$expr,na.rm=TRUE), max(sm$expr,na.rm=TRUE)),
    " NA:", sum(is.na(sm$expr)), "\n")
gmed <- median(sm$expr, na.rm=TRUE); cat("median:", gmed, "\n")
rs <- rowSums(sm$expr > gmed, na.rm=TRUE)
cat("rowSums> median: min", min(rs), "median", median(rs), "max", max(rs), "\n")
cat("detected:", sum(rs >= 0.5*ncol(sm$expr)), "/", nrow(sm$expr), "\n")
soft <- parse_soft(file.path(DATA_RAW,"GPL3921.soft.gz"))
cat("\nsoft dim:", paste(dim(soft),collapse="x"), "\n")
cat("soft cols:", paste(head(names(soft),12),collapse=" | "), "\n")
cat("soft ID head:", paste(head(soft$ID,3),collapse=", "), "\n")
p2s <- soft_probe2symbol(soft)
cat("p2s length:", length(p2s), " non-NA:", sum(!is.na(p2s)), "\n")
cat("overlap with series matrix rownames:", length(intersect(names(p2s), rownames(sm$expr))), "\n")
