# =============================================================================
# R21_sessioninfo.R
# -----------------------------------------------------------------------------
# Records the environment that produced the submitted numbers.
#
# The manuscript states that the full sessionInfo() record is deposited with the
# code, and no such record existed -- v1's Data Availability made the same kind
# of promise about a supplementary file that turned out to have no script behind
# it. This is that record, and this script is what regenerates it, so the file
# is an output of the repository rather than a pasted artifact.
#
# It loads the same libraries the pipeline loads, in the same order, through
# R00_config.R, so the versions listed are the versions the pipeline actually
# resolves -- not a hand-assembled list of what the authors believed they were
# running.
#
# Run: Rscript Code/Revision_v2/R21_sessioninfo.R
# =============================================================================
source("D:/R_projects/revision_analysis/Code/Revision_v2/R00_config.R")

# R06-R15 load these on top of the two R00 pulls in; list them here so the
# record covers every package any pipeline stage attaches.
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(DESeq2)
  library(GSVA)
  library(clusterProfiler)
  library(org.Hs.eg.db)
  library(survival)
  library(survminer)
  library(limma)
  library(matrixStats)
  library(dynamicTreeCut)
  library(TCGAbiolinks)
})

out <- file.path("D:/R_projects/revision_analysis/Code/Revision_v2", "sessionInfo.txt")
con <- file(out, "w")
writeLines(c(
  "# Environment record for the v2 analysis",
  "#",
  "# Generated by Code/Revision_v2/R21_sessioninfo.R, which loads the same",
  "# library set the pipeline loads and then writes sessionInfo(). Regenerate it",
  "# with:  Rscript Code/Revision_v2/R21_sessioninfo.R",
  "#",
  sprintf("# R00 config version: %s", if (exists("CONFIG_VERSION")) CONFIG_VERSION else "see R00_config.R"),
  ""), con)
close(con)

sink(out, append = TRUE)
print(sessionInfo())
sink()

cat("written:", out, "\n")
