# -*- coding: utf-8 -*-
"""
Rebuild the PLOS ONE v2 submission package from source.

WHY THIS FILE EXISTS
--------------------
The v2 package was assembled by hand on 2026-10-04. Only two of its six upload
files had a script behind them (`build_plos_docx_v2.py` for the manuscript,
`build_tracked_docx.py` for the tracked revision); the cover letter and the
response letter were pandoc'd ad hoc and the figures and SI PDF were copied by
hand. So a change to a title in the markdown had no path to the package, and the
package could not be rebuilt from the repository at all.

That is the same failure this repository was rebuilt to eliminate: an artifact in
a submission with no reproducible source. The first submission shipped a
supplementary PDF that no script in the repository could produce, and it turned
out to be from an abandoned analysis. A package you cannot rebuild is a package
you cannot check.

Run this after editing any of the four source documents. It rebuilds all four
docx and copies in the figures and SI PDF, which are generated by the R pipeline
(`R17_figures.R`, `R19_build_SI_pdf.py`) and are checked here by hash rather than
regenerated.

Usage:  python assemble_plos_v2.py
"""
import hashlib
import os
import shutil
import subprocess
import sys

ROOT = r"D:\R_projects\revision_analysis"
PKG = os.path.join(ROOT, "PLOS_ONE_Submission_v2")

# Document sources -> the numbered name they are uploaded under.
# (source, destination, builder) where builder is "pandoc" or a script path.
DOCS = [
    (os.path.join(ROOT, "Manuscript_PLOSONE_v2.md"),
     "03_Manuscript.docx", "build_plos_docx_v2.py"),
    (None,  # produced by build_tracked_docx.py, has no markdown of its own
     "04_Revised_Manuscript_with_Track_Changes.docx", "build_tracked_docx.py"),
    (os.path.join(ROOT, "Cover_Letter_PLOSONE_v2.md"),
     "01_Cover_Letter.docx", "pandoc"),
    (os.path.join(ROOT, "v2_output", "Response_to_Reviewers.md"),
     "02_Response_to_Reviewers.docx", "pandoc"),
]

# Copied rather than rebuilt. The source hash is asserted so that a stale or
# hand-edited package file cannot pass as current: the point of listing the
# expected source is to notice when the two have drifted apart.
COPIES = [
    (os.path.join(ROOT, "v2_output", "figures", "Fig1_harmonised_networks.pdf"),
     "Fig1.pdf"),
    (os.path.join(ROOT, "v2_output", "figures", "Fig2_pathway_mirror.pdf"),
     "Fig2.pdf"),
    (os.path.join(ROOT, "v2_output", "figures", "Fig3_same_organ_controls.pdf"),
     "Fig3.pdf"),
    (os.path.join(ROOT, "v2_output", "Supporting_Information_v2.pdf"),
     "05_Supporting_Information.pdf"),
]

# Files that were in the package on 2026-10-04 and are NOT upload items.
# Listed explicitly so that the assembly reports them rather than silently
# carrying them forward: `Fig1.docx` is a scratch paste-up of the Fig 1 panels
# (one empty paragraph, two embedded images), not something PLOS asks for.
NOT_UPLOADED = ["Fig1.docx", "00_提交清单_勿上传.md", "preview_png"]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def run(cmd, **kw):
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    p = subprocess.run(cmd, cwd=ROOT, env=env, **kw)
    if p.returncode != 0:
        sys.exit("FAILED: %s" % " ".join(cmd))


def pandoc_docx(src_md, dst_docx):
    """Markdown -> docx, matching the format the letters were shipped in.

    Deliberately plain: the letters in this package carry no explicit font,
    size or margin overrides, and adding `format_plos` here would silently
    re-typeset documents that have already been read by the authors. Change the
    formatting on purpose or not at all.
    """
    run(["pandoc", src_md, "-o", dst_docx,
         "--from", "markdown+superscript+subscript"])


def main():
    if not os.path.isdir(PKG):
        sys.exit("package directory not found: %s" % PKG)

    print("=" * 74)
    print("Rebuilding the four submission documents")
    print("=" * 74)

    for src, dst, builder in DOCS:
        print("\n[%s]" % dst)
        if builder == "pandoc":
            if not os.path.exists(src):
                sys.exit("  source missing: %s" % src)
            tmp = os.path.join(ROOT, "_pkg_tmp.docx")
            pandoc_docx(src, tmp)
            shutil.copy2(tmp, os.path.join(PKG, dst))
            os.remove(tmp)
            print("  pandoc %s -> %s" % (os.path.basename(src), dst))
        elif builder == "build_tracked_docx.py":
            run([sys.executable, builder])
            built = os.path.join(ROOT, "Manuscript_PLOSONE_v2_tracked.docx")
            shutil.copy2(built, os.path.join(PKG, dst))
            print("  %s -> %s" % (builder, dst))
        else:
            run([sys.executable, builder])
            built = os.path.join(ROOT, "Manuscript_PLOSONE_v2.docx")
            shutil.copy2(built, os.path.join(PKG, dst))
            print("  %s -> %s" % (builder, dst))

    print("\n" + "=" * 74)
    print("Copying figures and Supporting Information")
    print("=" * 74)
    for src, dst in COPIES:
        if not os.path.exists(src):
            sys.exit("  source missing: %s" % src)
        dst_path = os.path.join(PKG, dst)
        same = os.path.exists(dst_path) and sha256(src) == sha256(dst_path)
        shutil.copy2(src, dst_path)
        print("  %-34s -> %-30s %s"
              % (os.path.relpath(src, ROOT), dst,
                 "unchanged" if same else "UPDATED"))

    print("\n" + "=" * 74)
    print("Package contents")
    print("=" * 74)
    for name in sorted(os.listdir(PKG)):
        full = os.path.join(PKG, name)
        if os.path.isdir(full):
            print("      %-46s (directory)" % name)
            continue
        note = "  <- do not upload" if name in NOT_UPLOADED else ""
        print("  %-46s %8d B%s" % (name, os.path.getsize(full), note))

    print("\nUpload these six, and nothing else:")
    for name in ("01_Cover_Letter.docx", "02_Response_to_Reviewers.docx",
                 "03_Manuscript.docx",
                 "04_Revised_Manuscript_with_Track_Changes.docx",
                 "05_Supporting_Information.pdf",
                 "Fig1.pdf  Fig2.pdf  Fig3.pdf"):
        print("  " + name)
    print("\nThen run: python verify_all.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
